java_test(
    name = "AlpacaStockDataClientTest",
    srcs = ["AlpacaStockDataClientTest.java"],
    test_class = "test.java.com.algotrader.client.AlpacaStockDataClientTest",
    resources = ["//src/test/resources:test_env"],
    deps = [
        "//src/main/java/com/algotrader/client:clientlib",
        "//src/main/java/com/algotrader/dataclasses:datalib",
        "@maven//:junit_junit",
    ],
)

java_test(
    name = "AlpacaClientConstantsTest",
    srcs = ["AlpacaClientConstantsTest.java"],
    test_class = "test.java.com.algotrader.client.AlpacaClientConstantsTest",
    resources = ["//src/test/resources:test_env"],
    deps = [
        "//src/main/java/com/algotrader/client:clientlib",
        "@maven//:junit_junit",
    ]
)

java_test(
    name = "AlpacaStreamDataClientTest",
    srcs = ["AlpacaStreamDataClientTest.java"],
    test_class = "test.java.com.algotrader.client.AlpacaStreamDataClientTest",
    resources = ["//src/test/resources:test_env"],
    deps = [
        "//src/main/java/com/algotrader/client:clientlib",
        "//src/main/java/com/algotrader/dataclasses:datalib",
        "@maven//:junit_junit",
    ]
)